import { useEffect, useState } from 'react';
import { Alert, Btn, Select, Spinner } from '../ui';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../ui/dialog';
const DIFFICULTIES=[['EASY','Easy','Direct recall and one-step application'],['MEDIUM','Medium','Balanced classroom assessment'],['HARD','Hard','Deeper, lesson-grounded reasoning']];
export default function QuizGenerationModal({open,loading=false,error='',initialPrompt='',onCancel,onGenerate}){
  const[difficulty,setDifficulty]=useState('MEDIUM'),[questionCount,setQuestionCount]=useState(10);
  useEffect(()=>{if(open){setDifficulty('MEDIUM');setQuestionCount(10);}},[open]);
  return <Dialog open={open} onOpenChange={next=>{if(!next&&!loading)onCancel();}}><DialogContent showCloseButton={!loading} className="sm:max-w-lg"><DialogHeader><DialogTitle>Generate quiz draft</DialogTitle><DialogDescription>Select the question difficulty and length. Difficulty changes question complexity, not the student-facing title.</DialogDescription></DialogHeader>{loading&&<Alert type="info" label="In progress" title="Generating quiz draft" className="mb-0" actions={<Spinner size="md"/>}>Using the approved lesson context. This may take a few seconds.</Alert>}{error&&!loading&&<Alert type="error" label="Generation error" title="Quiz generation failed" className="mb-0">{error}</Alert>}<fieldset disabled={loading}><legend className="mb-2 text-sm font-medium text-slate-700 dark:text-slate-300">Question difficulty</legend><div className="grid gap-2 sm:grid-cols-3">{DIFFICULTIES.map(([value,label,hint])=><label key={value} className={`quiz-difficulty-option ${difficulty===value?'is-selected':''}`}><input type="radio" name="quiz-difficulty" value={value} checked={difficulty===value} onChange={()=>setDifficulty(value)}/><strong>{label}</strong><small>{hint}</small></label>)}</div></fieldset><label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Number of questions<Select className="mt-2" value={questionCount} disabled={loading} onChange={event=>setQuestionCount(Number(event.target.value))}>{[5,10,15,20].map(value=><option key={value} value={value}>{value}</option>)}</Select></label><DialogFooter><Btn variant="ghost" disabled={loading} onClick={onCancel}>Cancel</Btn><Btn disabled={loading} aria-busy={loading||undefined} onClick={()=>onGenerate({difficulty,questionCount,prompt:initialPrompt||`Generate a ${questionCount}-question quiz about this lesson.`})}>{loading?<><Spinner/>Generating…</>:error?'Retry generation':'Generate quiz'}</Btn></DialogFooter></DialogContent></Dialog>;
}
