const router=require('express').Router();
const rateLimit=require('express-rate-limit');
const authenticate=require('../middleware/authenticate');
const {authorizeActive}=require('../middleware/authorize');
const controller=require('../controllers/phase6.controller');
const solutions=require('../controllers/quiz-solution.controller');
const solutionUpload=require('../middleware/solutionSubmissionUpload');
const solutionAnalysisLimiter=rateLimit({windowMs:15*60*1000,max:20,standardHeaders:true,legacyHeaders:false,
  message:{success:false,error:'Too many solution-analysis requests. Please try again later.'}});
const student=[authenticate,authorizeActive('STUDENT')];
const instructor=[authenticate,authorizeActive('INSTRUCTOR')];
const admin=[authenticate,authorizeActive('ADMIN')];
const studentExportLimiter=rateLimit({windowMs:15*60*1000,max:20,standardHeaders:true,legacyHeaders:false,message:{success:false,error:'Too many lesson downloads. Please wait a few minutes and try again.'}});
router.get('/student/learning',...student,controller.dashboard);
router.get('/student/lessons/:lessonId',...student,controller.lesson);
router.get('/student/lessons/:lessonId/export/:format',studentExportLimiter,...student,controller.lessonExport);
router.post('/student/quizzes/:quizId/attempt',...student,controller.start);
router.get('/student/attempts/:attemptId',...student,controller.attempt);
router.put('/student/attempts/:attemptId/answers/:questionId',...student,controller.answer);
router.post('/student/attempts/:attemptId/submit',...student,controller.submit);
router.post('/student/attempts/:attemptId/answers/:questionId/solution',...student,solutionUpload,solutions.upload);
router.get('/quiz-attempt-answers/:answerId/solution-image',authenticate,authorizeActive('STUDENT','INSTRUCTOR'),solutions.image);
router.get('/instructor/sections/:sectionId/reviews',...instructor,solutions.sectionReviews);
router.get('/instructor/review-queue',...instructor,solutions.queue);
router.get('/instructor/quizzes/:quizId/attempts',...instructor,solutions.attempts);
router.get('/instructor/quizzes/:quizId/solutions',...instructor,solutions.list);
router.post('/instructor/quiz-answers/:answerId/recognize',...instructor,solutionAnalysisLimiter,solutions.recognize);
router.post('/instructor/quiz-answers/:answerId/analyze',...instructor,solutionAnalysisLimiter,solutions.analyze);
router.put('/instructor/quiz-answers/:answerId/grade',...instructor,solutions.grade);
router.get('/student/quiz-history',...student,controller.history);
router.get('/instructor/quizzes/:quizId/analytics',...instructor,controller.quizAnalytics);
router.get('/instructor/sections/:sectionId/analytics',...instructor,controller.sectionAnalytics);
router.get('/admin/system-evaluation',...admin,controller.systemEvaluation);
module.exports=router;
