import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, X } from '../icons';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../ui/dialog';
import ProtectedCaptureImage from '../hardware/ProtectedCaptureImage';
export default function ImageLightbox({open,onClose,title,subtitle,statusBadge,protectedUrl,imageUrl,alt,positionLabel,onPrevious,onNext}){
  const[actualSize,setActualSize]=useState(false);
  useEffect(()=>{if(!open)return undefined;setActualSize(false);function key(event){if(event.key==='ArrowLeft'&&onPrevious)onPrevious();if(event.key==='ArrowRight'&&onNext)onNext();}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[open,onPrevious,onNext]);
  const imageClass=actualSize?'h-auto w-auto max-w-none object-contain':'max-h-[calc(100dvh-14rem)] w-full object-contain sm:max-h-[calc(100dvh-12rem)]';
  return <Dialog open={open} onOpenChange={next=>{if(!next)onClose();}}><DialogContent showCloseButton={false} className="flex max-h-[calc(100dvh-1rem)] max-w-[min(96vw,1500px)] flex-col gap-0 overflow-hidden p-0 sm:max-h-[calc(100dvh-2rem)] sm:max-w-[min(96vw,1500px)]"><header className="flex shrink-0 flex-wrap items-start justify-between gap-3 border-b border-border px-3 py-3 dark:border-border sm:px-5"><DialogHeader className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><DialogTitle>{title||'Image viewer'}</DialogTitle>{statusBadge}</div>{subtitle&&<DialogDescription>{subtitle}</DialogDescription>}</DialogHeader><div className="flex shrink-0 items-center gap-2"><button type="button" onClick={()=>setActualSize(value=>!value)} className="min-h-11 rounded-lg border border-border bg-card px-3 text-xs font-semibold text-foreground hover:bg-surface-subtle dark:border-border dark:bg-surface dark:text-foreground">{actualSize?'Fit to screen':'Actual size'}</button><button type="button" onClick={onClose} aria-label="Close image viewer" className="grid h-11 w-11 place-items-center rounded-lg text-muted-foreground hover:bg-destructive-subtle hover:text-destructive-subtle-foreground dark:text-muted-foreground dark:hover:bg-destructive-subtle"><X size={20}/></button></div></header><div className={`min-h-0 flex-1 bg-slate-950 ${actualSize?'overflow-auto':'overflow-hidden'}`}><div className={`flex min-h-full min-w-full items-center justify-center ${actualSize?'w-max':''}`}>{protectedUrl?<ProtectedCaptureImage url={protectedUrl} alt={alt} className={imageClass}/>:<img src={imageUrl} alt={alt} className={imageClass}/>}</div></div>{(positionLabel||onPrevious||onNext)&&<footer className="flex shrink-0 items-center justify-between gap-3 border-t border-border px-3 py-3 dark:border-border sm:px-5"><button type="button" onClick={onPrevious} disabled={!onPrevious} className="inline-flex min-h-11 items-center gap-1.5 rounded-lg px-3 text-xs font-semibold text-muted-foreground hover:bg-surface-elevated disabled:pointer-events-none disabled:opacity-30 dark:text-muted-foreground"><ArrowLeft size={16}/> Previous</button><span className="text-center text-xs font-medium text-muted-foreground dark:text-muted-foreground">{positionLabel}</span><button type="button" onClick={onNext} disabled={!onNext} className="inline-flex min-h-11 items-center gap-1.5 rounded-lg px-3 text-xs font-semibold text-muted-foreground hover:bg-surface-elevated disabled:pointer-events-none disabled:opacity-30 dark:text-muted-foreground">Next <ArrowRight size={16}/></button></footer>}</DialogContent></Dialog>;
}