import { useEffect, useState } from 'react';
import api from '../../services/api';
import { ArrowLeft, ArrowRight, X } from '../icons';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../ui/dialog';
export default function PdfViewer({open,onClose,material}){
  const[url,setUrl]=useState(''),[page,setPage]=useState(1),[error,setError]=useState('');const pages=material?.pageCount||1;
  useEffect(()=>{if(!open||!material)return undefined;let active=true,objectUrl='';setPage(Math.min(pages,Math.max(1,material.initialPage||1)));setError('');api.get(material.fileUrl,{responseType:'blob'}).then(response=>{if(!active)return;objectUrl=URL.createObjectURL(new Blob([response.data],{type:'application/pdf'}));setUrl(objectUrl);}).catch(()=>active&&setError('The protected PDF could not be loaded.'));return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);setUrl('');};},[open,material,pages]);
  useEffect(()=>{if(!open)return undefined;const key=event=>{if(event.key==='ArrowLeft')setPage(value=>Math.max(1,value-1));if(event.key==='ArrowRight')setPage(value=>Math.min(pages,value+1));};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[open,pages]);
  if(!material)return null;
  return <Dialog open={open} onOpenChange={next=>{if(!next)onClose();}}><DialogContent showCloseButton={false} className="flex h-[calc(100dvh-1rem)] max-w-[1500px] flex-col gap-0 overflow-hidden p-0 sm:h-[calc(100dvh-2rem)] sm:max-w-[min(96vw,1500px)]"><header className="flex items-center justify-between gap-3 border-b border-slate-200 px-4 py-3 dark:border-slate-700"><DialogHeader className="min-w-0"><DialogTitle className="truncate">{material.originalFilename}</DialogTitle><DialogDescription>{pages} {pages===1?'page':'pages'} • Protected lesson material</DialogDescription></DialogHeader><button type="button" aria-label="Close PDF viewer" onClick={onClose} className="grid h-11 w-11 place-items-center rounded-lg text-slate-500 hover:bg-red-50 hover:text-red-600 dark:text-slate-300 dark:hover:bg-red-400/10"><X size={20}/></button></header><div className="min-h-0 flex-1 bg-slate-900">{error?<div className="grid h-full place-items-center p-6 text-sm text-red-300">{error}</div>:url?<iframe key={page} title={material.originalFilename} src={`${url}#page=${page}&view=FitH&toolbar=0`} className="h-full w-full border-0"/>:<div className="grid h-full place-items-center text-sm text-slate-300">Loading protected PDF…</div>}</div><footer className="flex items-center justify-between border-t border-slate-200 px-3 py-3 dark:border-slate-700"><button type="button" disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="inline-flex min-h-11 items-center gap-1 rounded-lg px-3 text-sm font-semibold disabled:opacity-30 dark:text-white"><ArrowLeft size={16}/> Previous</button><span className="text-sm font-semibold text-slate-700 dark:text-slate-200">Page {page} of {pages}</span><button type="button" disabled={page>=pages} onClick={()=>setPage(value=>value+1)} className="inline-flex min-h-11 items-center gap-1 rounded-lg px-3 text-sm font-semibold disabled:opacity-30 dark:text-white">Next <ArrowRight size={16}/></button></footer></DialogContent></Dialog>;
}