import { useEffect, useState } from 'react';
import DashboardLayout from '../../layouts/DashboardLayout';
import { Alert, Card, LoadingState, PageHeader } from '../../components/ui';
import { getSystemEvaluation } from '../../services/phase6Api';

const percent=value=>value==null?'Not evaluated':`${Math.round(value*10)/10}%`;
const duration=value=>value==null?'Not evaluated':`${(value/1000).toFixed(1)}s`;
export default function SystemEvaluation(){const[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{getSystemEvaluation().then(setData).catch(e=>setError(e.response?.data?.error||'Unable to load system evaluation.'));},[]);return <DashboardLayout><PageHeader title="System Evaluation" subtitle="Aggregate SEA-IT-SOLVED processing and research indicators."/>{error&&<Alert>{error}</Alert>}{!data?<LoadingState text="Calculating system indicators…"/>:<div className="grid gap-5 lg:grid-cols-2"><MetricGroup title="Whiteboard Recognition" data={[['Jobs',data.recognition.jobs],['Successful',data.recognition.successful],['Failed',data.recognition.failed],['Success rate',percent(data.recognition.successRate)],['Average processing time',duration(data.recognition.averageProcessingMs)]]}/><MetricGroup title="Transcription" data={[['Jobs',data.transcription.jobs],['Successful',data.transcription.successful],['Failed',data.transcription.failed],['Success rate',percent(data.transcription.successRate)],['Average processing time',duration(data.transcription.averageProcessingMs)]]}/><MetricGroup title="AI Generation" data={[['Generated lesson materials',data.aiGeneration.generatedLessonMaterials],['Generated quizzes',data.aiGeneration.generatedQuizzes],['Failures',data.aiGeneration.failures??'Not evaluated'],['Average processing time',duration(data.aiGeneration.averageProcessingMs)]]}/><MetricGroup title="Context Review" data={[['Total chunks',data.contextReview.total],['Accepted unchanged',data.contextReview.acceptedUnchanged],['Edited',data.contextReview.edited],['Removed',data.contextReview.removed],['Acceptance rate',percent(data.contextReview.acceptanceRate)],['Correction rate',percent(data.contextReview.correctionRate)]]}/><Card className="p-5 lg:col-span-2"><h2 className="font-black text-slate-900 dark:text-white">Ground-truth Research Metrics</h2><p className="mt-1 text-xs text-slate-500">Metrics remain unevaluated until a validated ground-truth dataset exists.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['CER',data.groundTruth.cer],['WER',data.groundTruth.wer],['Equation Exact Match',data.groundTruth.equationExactMatch],['Timestamp MAE',data.groundTruth.timestampMae],['Grounded Content Evaluation',data.groundTruth.groundedContentEvaluation]].map(([label,value])=><Metric key={label} label={label} value={value??'Not evaluated'}/>)}</div></Card></div>}</DashboardLayout>;}
function MetricGroup({title,data}){return <Card className="p-5"><h2 className="font-black text-slate-900 dark:text-white">{title}</h2><dl className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{data.map(([label,value])=><Metric key={label} label={label} value={value}/>)}</dl></Card>;}
function Metric({label,value}){return <div className="rounded-xl bg-slate-100/70 p-3 dark:bg-white/[.05]"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words text-lg font-black text-slate-900 dark:text-white">{value}</dd></div>;}
