import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import { Alert, Card, EmptyState, LoadingState, PageHeader, StatCard } from '../../components/ui';
import { ArrowLeft, Chart } from '../../components/icons';
import GeneratedContent from '../../components/reasoning/GeneratedContent';
import { getQuizAnalytics } from '../../services/phase6Api';
import { safeSectionReturnPath, sectionOriginFromState, sectionOriginState, sectionReturnPath } from '../../utils/instructorLessonNavigation';

const percent=value=>value==null?'—':`${Math.round(value*10)/10}%`;
function Bar({value,color='bg-primary'}){return <div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200 dark:bg-white/10"><div className={`h-full ${color}`} style={{width:`${Math.max(0,Math.min(100,value||0))}%`}}/></div>;}
function safeInstructorReturnPath(value) {
  const path = String(value || '');
  return /^\/instructor\/lessons\/[^/?#]+\/review(?:[?#].*)?$/.test(path)
    || safeSectionReturnPath(path)
    || /^\/instructor\/sections\/[^/?#]+(?:\?tab=analytics)?$/.test(path)
    ? path : '';
}
export default function InstructorQuizAnalytics(){
  const{quizId}=useParams();const location=useLocation();const[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selectedId,setSelectedId]=useState('');
  useEffect(()=>{getQuizAnalytics(quizId).then(value=>{setData(value);setSelectedId(value.questions?.[0]?.id||'');}).catch(e=>setError(e.response?.data?.error||'Unable to load analytics.')).finally(()=>setLoading(false));},[quizId]);
  const selected=useMemo(()=>data?.questions.find(q=>q.id===selectedId)||null,[data,selectedId]);
  if(loading)return <DashboardLayout><LoadingState text="Calculating quiz analytics…"/></DashboardLayout>;
  if(!data)return <DashboardLayout><Alert>{error}</Alert></DashboardLayout>;
  const o=data.overview;
  const origin=safeInstructorReturnPath(location.state?.from||location.state?.returnTo);
  const lessonFallback=data.quiz.lessonId?`/instructor/lessons/${data.quiz.lessonId}/review?view=workspace`:'';
  const backTo=origin||lessonFallback||`/instructor/sections/${data.quiz.sectionId}?tab=analytics`;
  const returnsToLesson=backTo.startsWith('/instructor/lessons/');
  const higherLevelOrigin=sectionOriginFromState(location.state)||sectionReturnPath(data.quiz.sectionId,'reviews');
  const lessonBackState=sectionOriginState(location.state,higherLevelOrigin,{focusQuizId:data.quiz.id});
  return <DashboardLayout><Link to={backTo} replace state={returnsToLesson?lessonBackState:undefined} className="mb-4 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-slate-600 dark:text-slate-300"><ArrowLeft size={17}/>{returnsToLesson?'Back to Lesson Workspace':'Back to Analytics'}</Link><PageHeader title={data.quiz.title} subtitle={`${data.quiz.sectionName} • Student performance analytics`}/>{error&&<Alert>{error}</Alert>}
    <section aria-labelledby="overview-title"><div className="analytics-heading-row"><div><h2 id="overview-title">Quiz overview</h2><p>Submission and score summary for this assessment.</p></div><span>{o.submitted} submitted · Median {percent(o.medianPercentage)}</span></div><div className="analytics-primary-metrics"><StatCard value={o.enrolled} label="Students"/><StatCard value={percent(o.submissionRate)} label="Submission Rate"/><StatCard value={percent(o.averagePercentage)} label="Quiz Average"/><StatCard value={o.lowestPercentage==null&&o.highestPercentage==null?'—':`${percent(o.lowestPercentage)} – ${percent(o.highestPercentage)}`} label="Score Range"/></div></section>
    <Card className="mt-5 p-4 sm:p-5"><h2 className="font-black text-slate-900 dark:text-white">Score Distribution</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{data.scoreDistribution.map(range=><div key={range.label} className="rounded-xl bg-slate-100/70 p-3 text-center dark:bg-white/[.05]"><strong className="block text-xl text-slate-900 dark:text-white">{range.count}</strong><span className="text-xs text-slate-500">{range.label}</span></div>)}</div></Card>
    <div className="mt-6 grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(320px,.85fr)]"><Card className="p-4 sm:p-5"><h2 className="font-black text-slate-900 dark:text-white">Question Performance</h2><p className="mt-1 text-xs text-slate-500">Select a question for response details.</p>{data.questions.length?<div className="mt-4 space-y-3">{data.questions.map(q=><button key={q.id} type="button" onClick={()=>setSelectedId(q.id)} className={`analytics-question-row ${selectedId===q.id?'is-selected':''}`}><div className="flex justify-between gap-4 text-sm"><span><strong>Q{q.order}</strong> · {q.topic}</span><span className="shrink-0 font-black">{q.percentageCorrect==null?'Not scored':percent(q.percentageCorrect)}</span></div><Bar value={q.percentageCorrect} color={q.percentageCorrect!=null&&q.percentageCorrect<50?'bg-amber-500':'bg-primary'}/><p>{q.correct} correct · {q.incorrect??0} incorrect · {q.answered} answered</p></button>)}</div>:<EmptyState icon={<Chart/>} title="No questions"/>}</Card>
      <Card className="p-4 sm:p-5"><h2 className="font-black text-slate-900 dark:text-white">Question Drilldown</h2>{selected?<div className="mt-4"><p className="text-xs font-black uppercase tracking-widest text-primary-subtle-foreground">Question {selected.order}</p><div className="mt-2 text-base font-bold"><GeneratedContent markdown={selected.prompt}/></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Correct" value={selected.correct}/><Mini label="Incorrect" value={selected.incorrect??'—'}/><Mini label="Correct" value={percent(selected.percentageCorrect)}/></div>{selected.responseDistribution?.length>0&&<div className="mt-5 space-y-2"><h3 className="text-sm font-black text-slate-800 dark:text-white">Response Distribution</h3>{selected.responseDistribution.map(item=><div key={item.label} className={`analytics-distribution ${item.isCorrect?'is-correct':''}`}><strong>{item.label}</strong><div className="min-w-0"><GeneratedContent markdown={item.choice}/></div><span>{item.count} {item.count===1?'student':'students'}</span></div>)}{selected.mostSelectedIncorrect&&<p className="mt-3 text-xs text-amber-700 dark:text-amber-200">Most-selected incorrect choice: <strong>{selected.mostSelectedIncorrect.label}</strong> ({selected.mostSelectedIncorrect.count})</p>}</div>}</div>:<p className="mt-4 text-sm text-slate-500">Select a question.</p>}</Card></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-5"><h2 className="font-black text-slate-900 dark:text-white">Topic Performance</h2>{data.topics.length?<div className="mt-4 space-y-4">{data.topics.map(t=><div key={t.topic}><div className="flex justify-between text-sm"><span>{t.topic}</span><strong>{percent(t.percentage)}</strong></div><Bar value={t.percentage}/><p className="mt-1 text-xs text-slate-500">{t.correct} correct of {t.scored} scored responses</p></div>)}</div>:<p className="mt-4 text-sm text-slate-500">No grounded topic metadata is available.</p>}</Card><Card className="p-5"><h2 className="font-black text-slate-900 dark:text-white">Most Missed Questions</h2>{data.mostMissed.length?<ol className="mt-3 space-y-2">{data.mostMissed.map(q=><li key={q.id}><button type="button" onClick={()=>setSelectedId(q.id)} className="w-full rounded-xl bg-amber-500/10 p-3 text-left text-sm"><strong>Q{q.order}</strong> · {percent(q.percentageCorrect)} correct</button></li>)}</ol>:<p className="mt-4 text-sm text-slate-500">No scored responses yet.</p>}</Card></div>
    <Card className="mt-5 p-4 sm:p-5"><h2 className="font-black text-slate-900 dark:text-white">Student Results</h2><p className="mt-1 text-xs text-slate-500">Factual submitted assessment results.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.students.map(student=><article key={student.id} className="analytics-student-card"><div><strong>{student.name}</strong><span>{student.studentNumber||'No student number'}</span></div><dl><Mini label="Score" value={`${student.score}/${student.maxScore}`}/><Mini label="Percentage" value={percent(student.percentage)}/><Mini label="Missed" value={student.questionsMissed}/></dl>{student.topics?.length>0&&<details><summary>Topic performance</summary><ul>{student.topics.map(topic=><li key={topic.topic}><span>{topic.topic}</span><strong>{percent(topic.percentage)}</strong></li>)}</ul></details>}</article>)}</div>{!data.students.length&&<p className="py-6 text-center text-sm text-slate-500">No submissions yet.</p>}</Card>
  </DashboardLayout>;
}
function Mini({label,value}){return <div className="rounded-lg bg-slate-100/70 p-2 dark:bg-white/[.05]"><dt className="text-[10px] uppercase text-slate-500">{label}</dt><dd className="mt-1 font-black text-slate-900 dark:text-white">{value}</dd></div>;}
