import { useEffect, useMemo, useState } from 'react';
import { useLocation, useParams } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import { Alert, BackButton, Card, EmptyState, LoadingState, PageHeader, StatCard } from '../../components/ui';
import { Chart } from '../../components/icons';
import GeneratedContent from '../../components/reasoning/GeneratedContent';
import { getQuizAnalytics } from '../../services/phase6Api';
import { safeSectionReturnPath, sectionOriginFromState, sectionOriginState, sectionReturnPath } from '../../utils/instructorLessonNavigation';
import { analyticsHeadingClassName, analyticsMetricsClassName } from '../../components/analytics/analyticsStyles';

const percent=value=>value==null?'—':`${Math.round(value*10)/10}%`;
function Bar({value,color='bg-primary'}){return <div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200 dark:bg-card/10"><div className={`h-full ${color}`} style={{width:`${Math.max(0,Math.min(100,value||0))}%`}}/></div>;}
function safeInstructorReturnPath(value) {
  const path = String(value || '');
  return /^\/instructor\/lessons\/[^/?#]+\/review(?:[?#].*)?$/.test(path)
    || safeSectionReturnPath(path)
    || /^\/instructor\/sections\/[^/?#]+(?:\?tab=analytics)?$/.test(path)
    ? path : '';
}
export default function InstructorQuizAnalytics(){
  const{quizId}=useParams();const location=useLocation();const[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selectedId,setSelectedId]=useState('');
  useEffect(()=>{getQuizAnalytics(quizId).then(value=>{setData(value);setSelectedId(value.questions?.[0]?.id||'');}).catch(e=>setError(e.response?.data?.error||'Unable to load analytics.')).finally(()=>setLoading(false));},[quizId]);
  const selected=useMemo(()=>data?.questions.find(q=>q.id===selectedId)||null,[data,selectedId]);
  if(loading)return <DashboardLayout><LoadingState text="Calculating quiz analytics…"/></DashboardLayout>;
  if(!data)return <DashboardLayout><Alert>{error}</Alert></DashboardLayout>;
  const o=data.overview;
  const origin=safeInstructorReturnPath(location.state?.from||location.state?.returnTo);
  const lessonFallback=data.quiz.lessonId?`/instructor/lessons/${data.quiz.lessonId}/review?view=workspace`:'';
  const backTo=origin||lessonFallback||`/instructor/sections/${data.quiz.sectionId}?tab=analytics`;
  const returnsToLesson=backTo.startsWith('/instructor/lessons/');
  const higherLevelOrigin=sectionOriginFromState(location.state)||sectionReturnPath(data.quiz.sectionId,'reviews');
  const lessonBackState=sectionOriginState(location.state,higherLevelOrigin,{focusQuizId:data.quiz.id});
  return <DashboardLayout><BackButton to={backTo} replace state={returnsToLesson?lessonBackState:undefined}>{returnsToLesson?'Back to Lesson Workspace':'Back to Analytics'}</BackButton><PageHeader title={<GeneratedContent markdown={data.quiz.title} quizText inline/>} subtitle={`${data.quiz.sectionName} • Student performance analytics`}/>{error&&<Alert>{error}</Alert>}
    <section aria-labelledby="overview-title"><div className={analyticsHeadingClassName}><div><h2 id="overview-title">Quiz overview</h2><p>Submission and score summary for this assessment.</p></div><span>{o.submitted} submitted · Median {percent(o.medianPercentage)}</span></div><div className={analyticsMetricsClassName}><StatCard value={o.enrolled} label="Students"/><StatCard value={percent(o.submissionRate)} label="Submission Rate"/><StatCard value={percent(o.averagePercentage)} label="Quiz Average"/><StatCard value={o.lowestPercentage==null&&o.highestPercentage==null?'—':`${percent(o.lowestPercentage)} – ${percent(o.highestPercentage)}`} label="Score Range"/></div></section>
    <Card className="mt-5 p-4 sm:p-5"><h2 className="font-black text-foreground dark:text-foreground">Score Distribution</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{data.scoreDistribution.map(range=><div key={range.label} className="rounded-xl bg-surface-elevated/70 p-3 text-center dark:bg-card/[.05]"><strong className="block text-xl text-foreground dark:text-foreground">{range.count}</strong><span className="text-xs text-muted-foreground">{range.label}</span></div>)}</div></Card>
    <div className="mt-6 grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(320px,.85fr)]"><Card className="p-4 sm:p-5"><h2 className="font-black text-foreground dark:text-foreground">Question Performance</h2><p className="mt-1 text-xs text-muted-foreground">Select a question for response details.</p>{data.questions.length?<div className="mt-4 space-y-3">{data.questions.map(q=>{const isSelected=selectedId===q.id;return <button key={q.id} type="button" onClick={()=>setSelectedId(q.id)} className={`block w-full min-w-0 rounded-[.85rem] border p-3 text-left transition-[border-color,background-color,transform] hover:border-slate-400 [&>p]:mt-[.35rem] [&>p]:text-[.68rem] [&>p]:text-muted-foreground ${isSelected?'border-primary bg-primary/[.07] shadow-[0_0_0_2px_hsl(var(--primary)/.1)]':'border-slate-400/25 dark:border-border'}`}><div className="flex justify-between gap-4 text-sm"><span><strong>Q{q.order}</strong> · <GeneratedContent markdown={q.topic} quizText inline/></span><span className="shrink-0 font-black">{q.percentageCorrect==null?'Not scored':percent(q.percentageCorrect)}</span></div><Bar value={q.percentageCorrect} color={q.percentageCorrect!=null&&q.percentageCorrect<50?'bg-warning':'bg-primary'}/><p>{q.correct} correct · {q.incorrect??0} incorrect · {q.answered} answered</p></button>;})}</div>:<EmptyState icon={<Chart/>} title="No questions"/>}</Card>
      <Card className="p-4 sm:p-5"><h2 className="font-black text-foreground dark:text-foreground">Question Drilldown</h2>{selected?<div className="mt-4"><p className="text-xs font-black uppercase tracking-widest text-primary-subtle-foreground">Question {selected.order}</p><div className="mt-2 text-base font-bold"><GeneratedContent markdown={selected.prompt}/></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Correct" value={selected.correct}/><Mini label="Incorrect" value={selected.incorrect??'—'}/><Mini label="Correct" value={percent(selected.percentageCorrect)}/></div>{selected.responseDistribution?.length>0&&<div className="mt-5 space-y-2"><h3 className="text-sm font-black text-foreground dark:text-foreground">Response Distribution</h3>{selected.responseDistribution.map(item=><div key={item.label} className={`grid min-w-0 grid-cols-[1.3rem_minmax(0,1fr)] items-center gap-2 rounded-[.7rem] border px-[.65rem] py-[.55rem] text-[.72rem] sm:grid-cols-[1.5rem_minmax(0,1fr)_auto] [&_.generated-doc-markdown]:font-sans [&_.generated-doc-markdown]:text-xs [&>span]:col-start-2 sm:[&>span]:col-auto ${item.isCorrect?'border-success/25 bg-success-subtle dark:bg-success-subtle':'border-border'}`}><strong>{item.label}</strong><div className="min-w-0"><GeneratedContent markdown={item.choice}/></div><span>{item.count} {item.count===1?'student':'students'}</span></div>)}{selected.mostSelectedIncorrect&&<p className="mt-3 text-xs text-warning-subtle-foreground dark:text-warning-subtle-foreground">Most-selected incorrect choice: <strong>{selected.mostSelectedIncorrect.label}</strong> ({selected.mostSelectedIncorrect.count})</p>}</div>}</div>:<p className="mt-4 text-sm text-muted-foreground">Select a question.</p>}</Card></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-5"><h2 className="font-black text-foreground dark:text-foreground">Topic Performance</h2>{data.topics.length?<div className="mt-4 space-y-4">{data.topics.map(t=><div key={t.topic}><div className="flex justify-between text-sm"><span><GeneratedContent markdown={t.topic} quizText inline/></span><strong>{percent(t.percentage)}</strong></div><Bar value={t.percentage}/><p className="mt-1 text-xs text-muted-foreground">{t.correct} correct of {t.scored} scored responses</p></div>)}</div>:<p className="mt-4 text-sm text-muted-foreground">No grounded topic metadata is available.</p>}</Card><Card className="p-5"><h2 className="font-black text-foreground dark:text-foreground">Most Missed Questions</h2>{data.mostMissed.length?<ol className="mt-3 space-y-2">{data.mostMissed.map(q=><li key={q.id}><button type="button" onClick={()=>setSelectedId(q.id)} className="w-full rounded-xl bg-warning-subtle p-3 text-left text-sm"><strong>Q{q.order}</strong> · {percent(q.percentageCorrect)} correct</button></li>)}</ol>:<p className="mt-4 text-sm text-muted-foreground">No scored responses yet.</p>}</Card></div>
    <Card className="mt-5 p-4 sm:p-5"><h2 className="font-black text-foreground dark:text-foreground">Student Results</h2><p className="mt-1 text-xs text-muted-foreground">Factual submitted assessment results.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.students.map(student=><article key={student.id} className="min-w-0 rounded-[.9rem] border border-slate-400/25 p-[.85rem] text-foreground dark:border-border dark:text-foreground [&>div:first-child]:flex [&>div:first-child]:min-w-0 [&>div:first-child]:flex-col [&>div:first-child_span]:text-[.68rem] [&>div:first-child_span]:text-muted-foreground [&_dl]:mt-[.65rem] [&_dl]:grid [&_dl]:grid-cols-2 [&_dl]:gap-[.4rem] sm:[&_dl]:grid-cols-3 [&_details]:mt-[.65rem] [&_details]:text-[.7rem] [&_summary]:cursor-pointer [&_summary]:font-extrabold [&_summary]:text-primary-subtle-foreground [&_li]:mt-[.35rem] [&_li]:flex [&_li]:justify-between [&_li]:gap-2"><div><strong>{student.name}</strong><span>{student.studentNumber||'No student number'}</span></div><dl><Mini label="Score" value={`${student.score}/${student.maxScore}`}/><Mini label="Percentage" value={percent(student.percentage)}/><Mini label="Missed" value={student.questionsMissed}/></dl>{student.topics?.length>0&&<details><summary>Topic performance</summary><ul>{student.topics.map(topic=><li key={topic.topic}><span><GeneratedContent markdown={topic.topic} quizText inline/></span><strong>{percent(topic.percentage)}</strong></li>)}</ul></details>}</article>)}</div>{!data.students.length&&<p className="py-6 text-center text-sm text-muted-foreground">No submissions yet.</p>}</Card>
  </DashboardLayout>;
}
function Mini({label,value}){return <div className="rounded-lg bg-surface-elevated/70 p-2 dark:bg-card/[.05]"><dt className="text-[10px] uppercase text-muted-foreground">{label}</dt><dd className="mt-1 font-black text-foreground dark:text-foreground">{value}</dd></div>;}
